// Generated by build.lua (bang)

pub const lua_src = "lua";
pub const src_path = "luax-libs";
pub const build_path = ".build/tmp";

pub const release = .ReleaseFast;
pub const strip = true;
pub const optim = "-O3";
pub const debug = "";

pub const lua_c_files = [_][]const u8 {
    "lua/lapi.c",
    "lua/lauxlib.c",
    "lua/lbaselib.c",
    "lua/lcode.c",
    "lua/lcorolib.c",
    "lua/lctype.c",
    "lua/ldblib.c",
    "lua/ldebug.c",
    "lua/ldo.c",
    "lua/ldump.c",
    "lua/lfunc.c",
    "lua/lgc.c",
    "lua/linit.c",
    "lua/liolib.c",
    "lua/llex.c",
    "lua/lmathlib.c",
    "lua/lmem.c",
    "lua/loadlib.c",
    "lua/lobject.c",
    "lua/lopcodes.c",
    "lua/loslib.c",
    "lua/lparser.c",
    "lua/lstate.c",
    "lua/lstring.c",
    "lua/lstrlib.c",
    "lua/ltable.c",
    "lua/ltablib.c",
    "lua/ltm.c",
    "lua/lundump.c",
    "lua/lutf8lib.c",
    "lua/lvm.c",
    "lua/lzio.c",
};

pub const lua_main_c_files = [_][]const u8 {
    "lua/lua.c",
};

pub const luax_main_c_files = [_][]const u8 {
    "luax/luax.c",
};

pub const luax_c_files = [_][]const u8 {
    "luax-libs/complex/complex.c",
    "luax-libs/crypt/crypt.c",
    "luax-libs/crypt/sha1.c",
    "luax-libs/fs/fs.c",
    "luax-libs/libluax.c",
    "luax-libs/lz4/lz4.c",
    "luax-libs/ps/ps.c",
    "luax-libs/rt0/rt0.c",
    "luax-libs/socket/luasocket.c",
    "luax-libs/std/std.c",
    "luax-libs/sys/sys.c",
    "luax-libs/term/term.c",
    "luax-libs/tools.c",
};

pub const third_party_c_files = [_][]const u8 {
    "ext/c/lcomplex/lcomplex.c",
    "ext/c/limath/limath.c",
    "ext/c/limath/src/imath.c",
    "ext/c/lpeg/lpcap.c",
    "ext/c/lpeg/lpcode.c",
    "ext/c/lpeg/lpcset.c",
    "ext/c/lpeg/lpprint.c",
    "ext/c/lpeg/lptree.c",
    "ext/c/lpeg/lpvm.c",
    "ext/c/lqmath/lqmath.c",
    "ext/c/lqmath/src/imrat.c",
    "ext/c/luasocket/auxiliar.c",
    "ext/c/luasocket/buffer.c",
    "ext/c/luasocket/compat.c",
    "ext/c/luasocket/except.c",
    "ext/c/luasocket/inet.c",
    "ext/c/luasocket/io.c",
    "ext/c/luasocket/luasocket.c",
    "ext/c/luasocket/mime.c",
    "ext/c/luasocket/options.c",
    "ext/c/luasocket/select.c",
    "ext/c/luasocket/tcp.c",
    "ext/c/luasocket/timeout.c",
    "ext/c/luasocket/udp.c",
    "ext/c/lz4/lib/lz4.c",
    "ext/c/lz4/lib/lz4file.c",
    "ext/c/lz4/lib/lz4frame.c",
    "ext/c/lz4/lib/lz4hc.c",
    "ext/c/lz4/lib/xxhash.c",
    "ext/c/mathx/lmathx.c",
};

pub const linux_third_party_c_files = [_][]const u8 {
    "ext/c/luasocket/serial.c",
    "ext/c/luasocket/unixdgram.c",
    "ext/c/luasocket/unixstream.c",
    "ext/c/luasocket/usocket.c",
    "ext/c/luasocket/unix.c",
};

pub const windows_third_party_c_files = [_][]const u8 {
    "ext/c/luasocket/wsocket.c",
};

