// This file is part of luax.
//
// luax is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// luax is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with luax.  If not, see <https://www.gnu.org/licenses/>.
//
// For further information about luax you can visit
// http://cdelord.fr/luax

// This file should later be generated by build.lua (bang)

pub const lua_c_files = [_][]const u8 {
    // Lua interpreter
    "lua/lapi.c",
    "lua/lauxlib.c",
    "lua/lbaselib.c",
    "lua/lcode.c",
    "lua/lcorolib.c",
    "lua/lctype.c",
    "lua/ldblib.c",
    "lua/ldebug.c",
    "lua/ldo.c",
    "lua/ldump.c",
    "lua/lfunc.c",
    "lua/lgc.c",
    "lua/linit.c",
    "lua/liolib.c",
    "lua/llex.c",
    "lua/lmathlib.c",
    "lua/lmem.c",
    "lua/loadlib.c",
    "lua/lobject.c",
    "lua/lopcodes.c",
    "lua/loslib.c",
    "lua/lparser.c",
    "lua/lstate.c",
    "lua/lstring.c",
    "lua/lstrlib.c",
    "lua/ltable.c",
    "lua/ltablib.c",
    "lua/ltm.c",
    "lua/lundump.c",
    "lua/lutf8lib.c",
    "lua/lvm.c",
    "lua/lzio.c",
};

pub const lua_main_c_files = [_][]const u8 {
    // Lua interpreter
    "lua/lua.c",
    //"lua/luac.c",
};

pub const luax_main_c_files = [_][]const u8 {
    // LuaX runtime
    "luax/luax.c",
};

pub const luax_c_files = [_][]const u8 {
    // LuaX library (static and dynamic)
    "luax-libs/rt0/rt0.c",
    "luax-libs/libluax.c",
    "luax-libs/tools.c",
    "luax-libs/std/std.c",
    "luax-libs/fs/fs.c",
    "luax-libs/ps/ps.c",
    "luax-libs/sys/sys.c",
    "luax-libs/crypt/crypt.c",
    "luax-libs/crypt/sha1.c",
    "luax-libs/complex/complex.c",
    "luax-libs/socket/luasocket.c",
    "luax-libs/lz4/lz4.c",
    "luax-libs/term/term.c",
};

pub const third_party_c_files = [_][]const u8 {
    // LuaX runtime
    "ext/c/lpeg/lpcap.c",
    "ext/c/lpeg/lpcode.c",
    "ext/c/lpeg/lpcset.c",
    "ext/c/lpeg/lpprint.c",
    "ext/c/lpeg/lptree.c",
    "ext/c/lpeg/lpvm.c",
    "ext/c/mathx/lmathx.c",
    "ext/c/limath/limath.c",
    "ext/c/limath/src/imath.c",
    "ext/c/lqmath/lqmath.c",
    "ext/c/lqmath/src/imrat.c",
    "ext/c/lcomplex/lcomplex.c",
    "ext/c/luasocket/auxiliar.c",
    "ext/c/luasocket/buffer.c",
    "ext/c/luasocket/compat.c",
    "ext/c/luasocket/except.c",
    "ext/c/luasocket/inet.c",
    "ext/c/luasocket/io.c",
    "ext/c/luasocket/luasocket.c",
    "ext/c/luasocket/mime.c",
    "ext/c/luasocket/options.c",
    "ext/c/luasocket/select.c",
    "ext/c/luasocket/tcp.c",
    "ext/c/luasocket/timeout.c",
    "ext/c/luasocket/udp.c",
    "ext/c/lz4/lz4.c",
    "ext/c/lz4/lz4file.c",
    "ext/c/lz4/lz4frame.c",
    "ext/c/lz4/lz4hc.c",
    "ext/c/lz4/xxhash.c",
};

pub const linux_third_party_c_files = [_][]const u8 {
    "ext/c/luasocket/serial.c",
    "ext/c/luasocket/unixdgram.c",
    "ext/c/luasocket/unixstream.c",
    "ext/c/luasocket/usocket.c",
    "ext/c/luasocket/unix.c",
};

pub const windows_third_party_c_files = [_][]const u8 {
    "ext/c/luasocket/wsocket.c",
};
