-- This file is part of bang.
--
-- bang is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- bang is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with bang.  If not, see <https://www.gnu.org/licenses/>.
--
-- For further information about bang you can visit
-- https://codeberg.org/cdsoft/bang

local F = require "F"

section [[
This file is generated by bang for test purpose.
Section comments can have multiple lines.
]]

ninja_required_version "1.10" -- lower than the version required by bang => should have no impact

require "test-module" -- this shall appear in the generator inputs

generator {
    implicit_in = {
        "foo",
        "bar",
    },
    another_variable = {
        "abc", "def",
    },
}

section "Atomic variables"

local v1 = var "var1" "string"
local v2 = var "var2" (42)
local v3 = var "var3" (true)

comment("v1        = "..v1)
comment("vars.var1 = "..vars.var1)
comment("v2        = "..v2)
comment("vars.var2 = "..vars.var2)
comment("v3        = "..v3)
comment("vars.var3 = "..vars.var3)
comment("vars%...: "..vars%"« var1 = $var1, var2 = $var2, var3 = $var3 »")

var "foo" "FOO"
var "bar" "bar is $foo"
var "baz" "baz is $foo and $bar"

comment("vars%... with recursive definitions: "..vars%"« baz = $baz »")
comment("vars%...: "..F.show(vars%{"$foo", {"$bar", "$baz"}}))

section "Compound variables"

local v4 = var "var4" {
    "string",
    42,
    true,
    {
        " foo  ",
        { },
        "  bar ",
        Nil,    -- equivalent to {}
        "   baz   ",
    },
}
comment("v4        = "..v4)
comment("vars.var4 = "..vars.var4)

section "Rules"

local cc = rule "cc" {
    description = "CC $out",
    command = {
        "gcc",
        "$cflags",
        "-c",
        "$in -o $out",
    },
}

comment("cc = "..F.show(cc))

section "Build statements"

local o1 = build "foo1.o" {"cc", {"foo1.c", "foo.h"}}

local o2 = build "foo2.o" {"cc", {"foo2.c", "foo.h"},
    implicit_in = {"a.dat", "b.dat"},
    implicit_out = {"a.log", "b.log"},
    order_only_deps = {"x.dat"},
    myvar = "myval",
}

comment("o1 = "..F.show(o1))
comment("o2 = "..F.show(o2))

phony "all" { "foo1.c", "foo2.c" }

local o3 = build {"foo3.o", "foo4.o foo5.o"} {"cc", {"foo3.c"}}

comment("o3 = "..F.show(o3))

section "Inheritance"

rule "r1" {
    command = "cmd1",
    -- this variable shall be moved to the build statements that use this rule
    implicit_in = {"i1", "i2"},
}

build "b1" { "r1",
    implicit_in = {"i3"},
    implicit_out = {"o1"},
}

rule "r2" {
    command = "cmd2",
    -- this variable shall be moved to the build statements that use this rule
    implicit_in = {"i4", "i5"},
}

build "b2" { "r2",
    implicit_out = {"o2"},
}

section "Embedded rules"

build "special_target.txt" { "file1.txt", "file2.txt",
    description = "a rule embedded inside a build statement",
    command = "cat $in > $out",
    implicit_in = "hidden_input",
    implicit_out = "hidden_output",
    depfile = "$out.d",
}

section "Nested rules (pipe simulation)"

rule "ypp.md" { command = "ypp $in -o $out" }
rule "panda.html" { command = "panda $in -o $out", implicit_in = "foo.css" }
rule "wkhtmltopdf.pdf" { command = "wkhtmltopdf $in $out", implicit_in = "pdf.css" }

local pipe1 = pipe { "ypp.md" }
local pipe2 = pipe { "ypp.md", "panda.html" }
local pipe3 = pipe { "ypp.md", "panda.html", "wkhtmltopdf.pdf" }

pipe1 "$builddir/doc/file1.md"   "doc/file1.md"
pipe2 "$builddir/doc/file2.html" "doc/file2.md"
pipe3 "$builddir/doc/file3.pdf"  { "doc/file3.md",
    implicit_in = "foo.in",
    implicit_out = "bar.out",
    variable = "baz",
}

section "Source preprocessor"

build.cc:executable "$builddir/foo-0" {
    "src.c",
    prepro { "conf.c.in", "version.c.in" },
    implicit_in = prepro { "conf.h.in" },
}

local new_prepro = prepro:new {
    dir = "$builddir/tmp",
    pp = build.ypp : new "ypp-prepro" : add "flags" { build.ypp_vars { X="x", Y="y" } }
}

build.cc:executable "$builddir/foo-1" {
    "src.c",
    new_prepro { "conf.c.in", "version.c.in" },
    implicit_in = new_prepro { "conf.h.in" },
}

section "Pools"

rule "link" {
    pool = pool "link_pool" { depth=4 },
    command = true,
}

build "link1" { "link" }
build "link2" { "link",
    pool = "",
}

section "Default"

default { "foo", "bar" }

section "Accumulations"

local xs = {}
acc(xs) "item1"
acc(xs) {"item2", "item3"}
acc(xs) {}
comment("xs = "..F.show(xs))

section "ls test"
ls "test" : foreach(comment)

section "ls test/*"
ls "test/*.*" : foreach(comment)

section "ls test/*.lua"
ls "test/*.lua" : foreach(comment)

section "ls test/**"
ls "test/**" : foreach(comment)

section "ls test/**.c"
ls "test/**.c" : foreach(comment)

section "ls test/**.lua"
ls "test/**.lua" : foreach(comment)

section "additional file"
local new_file = bang.output:dirname()/"new_file.txt"
local f = file(new_file)
f("Line", " ", 1, "\n")
f("Line", " ", 2, "\n")
comment(new_file.." should be created")

section "case expressions"

local opt1 = case "debug" {
    debug = "-g",
    fast  = "-O3",
    [Nil] = "-O2",
}

local opt2 = case "fast" {
    debug = "-g",
    fast  = "-O3",
    [Nil] = "-O2",
}

local opt3 = case "" {
    debug = "-g",
    fast  = "-O3",
    [Nil] = "-O2",
}

comment("opt1 = "..F.show(opt1))
comment("opt2 = "..F.show(opt2))
comment("opt3 = "..F.show(opt3))

local opt4 = case "debug" {
    debug     = "-g",
    fast      = "-O3",
}

local opt5 = case "fast" {
    debug     = "-g",
    fast      = "-O3",
}

local opt6 = case "" {
    debug     = "-g",
    fast      = "-O3",
}

comment("opt4 = "..F.show(opt4))
comment("opt5 = "..F.show(opt5))
comment("opt6 = "..F.show(opt6))

section "Command line arguments"
comment("The command line arguments are: "..F.show(arg))

section "Bang arguments"
comment("bang = "..F.show(bang, {indent=4}))

-- clean test
clean "$builddir"
clean "$builddir/foo"
clean "foo/bar"

-- install test
install.prefix "~/.local/pub/bang_test"
install "bin" "foo1.bin"
install "lib" "foo1.lib"
install "bin" { "foo2.bin", "foo3.bin" }

-- help test
help.name "Bang test"
help.description "A short description of the Ninja file for building $name"
help.epilog "More information at https://codeberg.org/cdsoft/bang"
help "target1" "description of target1"
help "target2" "description of target2"
help "target3-with-a-longer-name" "description of target3"
help "target4" "description of target4"

section "C compilers"

local target = "x86_64-linux-musl"

local zig = build.cc : new "my-zig"
    : set "builddir" "$builddir/tmp"
    : set "implicit_in" "$builddir/foo"
    : set "cc" { "zig cc", "-target", target }
    : add "cflags" { "-Og", "-g", "-Iinc" }
    : set "ar" "zig ar"
    : set "ld" { "zig ld", "-target", target }
    : add "ldflags" { "-pipe", "-s" }
    : add "ldlibs" "-lm"
    : add "soflags" { "-pipe" }
    : add "solibs" "-lz"

zig:compile "f1.o" { "f1.c" }
zig:static_lib "lib.a" {
    "f1.o",
    "f2.c",
}
zig:dynamic_lib "libf3.so" {
    "f1.o",
    "lib.a",
    "f3.c",
}
zig:executable "file.exe" {
    "f1.o",
    "lib.a",
    "f3.o",
    "f4.c",
}

build.compile_flags {
    "-O3",
    F.map(F.prefix"-I", {
        "$builddir",
        "$builddir/inc",
    }),
    "-DBAZ='$baz'",
}

section "C++ compilers"

local cpp = build.cpp

cpp:compile "f1++.o" { "f1.cc" }
cpp:static_lib "lib++.a" {
    "f1++.o",
    "f2.cpp",
}
cpp:dynamic_lib "libf3++.so" {
    "f1++.o",
    "lib++.a",
    "f3.cc",
}
cpp:executable "file++.exe" {
    "f1++.o",
    "lib++.a",
    "f3++.o",
    "f4.cc",
}

section "Cross compilation"

build.zigcc["macos-x86_64"]:dynamic_lib "mac_lib" { "x.a", "y.c" }
build.zigcc["macos-x86_64"]:executable "mac_exe" { "x.a", "y.c" }

build.zigcc["windows-x86_64"]:dynamic_lib "win_lib" { "x.a", "y.c" }
build.zigcc["windows-x86_64"]:executable "win_exe" { "x.a", "y.c" }

section "LuaX compiler (with a C compiler)"

build.luax.set_global "luax" "/path/to/luax"
build.luax.add_global "flags" { "-s", "-k", ("%q"):format("a \"super\" key") }

build.luax:add "flags" { "-x" }
build.luax.luax:add "flags" { "-y" }
build.luax.native:add "flags" "-q"

build.luax "hello-luax-1" { "hello.luax", "module.lua" }
build.luax.luax "hello-luax-2" { "hello.luax", "module.lua" }
build.luax.lua "hello-lua" { "hello.lua", "module.lua" }
build.luax.pandoc "hello-pandoc" { "hello.lua", "module.lua" }
build.luax.native "hello-native" { "hello.lua", "module.lua" }
F.foreach(require "targets", function(t)
    build.luax[t.name]("hello-"..t.name) { "hello.lua", "module.lua" }
end)

section "LuaX compiler (without any C compiler)"

local luaxnocc = build.luax : new"luax-nocc" : nocc()

luaxnocc "hello-luax-1-nocc" { "hello.luax", "module.lua" }

section "Document generators"

build.cat "cat.txt" "f.txt"
build.cp "copy.txt" "f.txt"

local tac = build.new "tac"
    : set "cmd" "tac"
    : add "implicit_in" { "x", "y" }
    : add "implicit_out" { "z" }

tac "rev.txt" { "f.txt",
    implicit_in = "foo.txt",
    other_arg = { "a", "b" },
}

rule "rule_1" {
    command = "r1",
}

rule "rule_2" {
    command = "r2",
}

local pipe_with_rules_and_generators = pipe {
    "rule_1",
    build.cat,
    "rule_2",
    tac,
}

pipe_with_rules_and_generators "bar.md" "foo.rst"

local pipe_with_implicit_extensions = pipe { build.ypp, build.pandoc }

pipe_with_implicit_extensions "doc-a.html" "doc.md"
pipe_with_implicit_extensions "doc-b.html" "doc.md.in"
pipe_with_implicit_extensions "doc-c.pdf"  "doc.md.in"

local ypp = build.ypp : new "myypp"
    : add "flags" {
        build.ypp_vars {
            X = "x",
            Y = "Hello, World!",
            Z = 42,
        },
        build.ypp_var "TABLE" {
            "A complex table",
            FOO = "foo",
            BAR = { 42 },
        },
    }

ypp "doc.md" "src/doc.md"

section "List of all files"

build.files() : foreach(comment)

section "List of files in $builddir/doc"

build.files(function(file) return file:has_prefix "$builddir/doc" end) : foreach(comment)

section "List of files in $builddir/doc"

build.files("$builddir/doc") : foreach(comment)

section "Archives"

build.cp "$builddir/release/foo-linux/bin/bar"       "$builddir/tmp/bar"
build.cp "$builddir/release/foo-linux/lib/bar.so"    "$builddir/tmp/bar.so"
build.cp "$builddir/release/foo-windows/bin/bar.exe" "$builddir/tmp/bar.exe"
build.cp "$builddir/release/foo-windows/lib/bar.dll" "$builddir/tmp/bar.dll"
build.cp "$builddir/release/foo-windows/lib/bar.lib" "$builddir/tmp/bar.lib"

build.tar "$builddir/foo-linux.tar" {
    base = "$builddir/release",
    name = "foo-linux",
}

build.tar "$builddir/foo-windows.tar" {
    base = "$builddir/release/foo-windows",
}

section "Images"

build.graphviz.dot.png "$builddir/dot.png" { "file.dot" }
build.asymptote.pdf "$builddir/asy.pdf" { "file.asy" }
